export enum EnvKeys {
  REDIS_URI = 'REDIS_URI',
  SERVICE_NAME = 'SERVICE_NAME',

  ACCESS_JWT_EXPIRES_IN = 'ACCESS_JWT_EXPIRES_IN',
  REFRESH_JWT_EXPIRES_IN = 'REFRESH_JWT_EXPIRES_IN',
  ACCESS_JWT_SECRET = 'ACCESS_JWT_SECRET',
}
